name: "Copilot Python Setup"
description: >
  Shared setup for GitHub Copilot coding agent in Python/uv projects.
  Installs uv, Python, project dependencies, and dev tools.
  Used via copilot-setup-steps.yml in each repo.

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.12"
  install-extras:
    description: "Space-separated list of extras to install (e.g., 'viz analysis')"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync --dev

    - name: Install extras (if specified)
      if: inputs.install-extras != ''
      shell: bash
      run: |
        for extra in ${{ inputs.install-extras }}; do
          uv sync --extra "$extra"
        done

    - name: Verify toolchain
      shell: bash
      run: |
        echo "Python: $(uv run python --version)"
        uv run ruff --version 2>/dev/null && echo "ruff: ok" || echo "ruff: not installed"
        uv run dprint --version 2>/dev/null && echo "dprint: ok" || echo "dprint: not installed"
        uv run pytest --version 2>/dev/null && echo "pytest: ok" || echo "pytest: not installed"
        echo "Toolchain ready."
