"""Tests for gemini-extension.json and hooks.json consistency."""

import json
from pathlib import Path

import pytest


class TestGeminiHooksJsonExists:
    """Test that hooks.json is generated correctly for Gemini CLI."""

    @pytest.fixture
    def root_dir(self) -> Path:
        """Return the repo root directory."""
        return Path(__file__).parent.parent

    @pytest.fixture
    def gemini_extension_json(self, root_dir: Path) -> Path:
        """Return the path to gemini-extension.json."""
        return root_dir / "gemini-extension.json"

    @pytest.fixture
    def dist_hooks_json(self, root_dir: Path) -> Path:
        """Return the path to dist/aops-core/hooks/hooks.json."""
        return root_dir / "dist" / "aops-core" / "hooks" / "hooks.json"

    def test_gemini_extension_json_exists(self, gemini_extension_json: Path) -> None:
        """Verify gemini-extension.json exists at root."""
        assert gemini_extension_json.exists(), (
            f"gemini-extension.json must exist at {gemini_extension_json}"
        )

    @pytest.mark.integration
    def test_hooks_json_exists_in_dist(self, dist_hooks_json: Path) -> None:
        """Verify hooks.json exists in dist/aops-core/hooks/.

        Gemini CLI reads hooks from hooks/hooks.json, NOT from gemini-extension.json.
        """
        if not dist_hooks_json.exists():
            pytest.skip(
                f"hooks.json must exist at {dist_hooks_json}. "
                "Gemini CLI reads hooks from this file, not gemini-extension.json. "
                "Run 'python scripts/build.py' to generate it."
            )

    @pytest.mark.integration
    def test_hooks_json_has_required_events(self, dist_hooks_json: Path) -> None:
        """Verify hooks.json contains all required Gemini lifecycle events.

        hooks.json is generated by build.py from the Claude hooks format.
        It must cover all lifecycle events that our router handles.
        """
        if not dist_hooks_json.exists():
            pytest.skip("hooks.json must exist in dist/")

        hooks_content = json.loads(dist_hooks_json.read_text())
        assert "hooks" in hooks_content, (
            f"hooks.json missing 'hooks' key: {list(hooks_content.keys())}"
        )

        hooks = hooks_content["hooks"]
        required_events = {"SessionStart", "SessionEnd", "BeforeTool", "AfterTool"}
        missing = required_events - set(hooks.keys())
        assert not missing, f"hooks.json missing required events: {missing}"

        # Each event must have at least one hook with a command
        for event, hook_list in hooks.items():
            assert len(hook_list) > 0, f"Event '{event}' has no hooks"
            for entry in hook_list:
                cmds = entry.get("hooks", [])
                assert len(cmds) > 0, f"Event '{event}' hook entry has no commands"
                for cmd in cmds:
                    assert cmd.get("type") == "command", f"Hook type must be 'command': {cmd}"
                    assert "router.py" in cmd.get("command", ""), (
                        f"Hook command must invoke router.py: {cmd.get('command')}"
                    )
