"""Unit tests for Milestone R4 (4-Tier Transcript System & Renderer Hardening).

Tests:
1. Generation of all 4 output tier artifacts (.controller.md, .full.md, .md, .html) + JSON sidecar.
2. XML/HTML tag escaping in prompts, thinking blocks, and tool outputs.
3. Wrapping large tool outputs (>500 chars or >10 lines) in <details><summary> Tool Output ({count} bytes) </summary>.
4. Explicit token/cost breakdown (controller_tokens, subagent_tokens, controller_cost_usd, subagent_cost_usd).
5. Sparse non-contiguous step_index sequence IDs causing no degradation warnings.
6. Unlinked subagent fallback rendering and inter-agent message echo deduplication.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from transcripts.domain.renderer import (
    _escape_html,
    build_json_sidecar,
    render_session_to_all_formats,
)
from transcripts.model import (
    NormalizedEvent,
    NormalizedSession,
    NormalizedToolCall,
    SubagentTranscript,
)
from transcripts.runner import process_single_session


class DummySkipCache:
    def is_skipped(self, key: str, fingerprint: str) -> bool:
        return False

    def mark_empty(self, key: str, fingerprint: str) -> None:
        pass

    def forget(self, key: str) -> None:
        pass


@pytest.fixture
def sample_session_with_subagents() -> NormalizedSession:
    subagent1 = SubagentTranscript(
        agent_id="sub_001",
        source_file=Path("agent-sub_001.jsonl"),
        agent_type="analyst",
        name="Analyst Worker",
        description="Analyze dataset features",
        parent_tool_use_id="toolu_spawn_1",
        tokens_used=400,
        cost_usd=0.004,
        spawn_depth=1,
        events=[
            NormalizedEvent(
                event_id="sub_e1",
                timestamp="2026-08-06T10:01:00Z",
                source="model",
                type="message",
                content="Analysis result for <dataset_table>",
            )
        ],
    )
    events = [
        NormalizedEvent(
            event_id="e1",
            timestamp="2026-08-06T10:00:00Z",
            source="user",
            type="message",
            content="Run <USER_REQUEST> analysis on <file_path>",
            meta={"is_human": True, "human_content": "Run <USER_REQUEST> analysis on <file_path>"},
        ),
        NormalizedEvent(
            event_id="e2",
            timestamp="2026-08-06T10:00:30Z",
            source="model",
            type="message",
            content="Delegating work to subagent",
            thinking="Thinking process with <thinking_tag> internal logic </thinking_tag>",
            tool_calls=[
                NormalizedToolCall(
                    name="Task",
                    args={"description": "Analyze dataset features"},
                    call_id="toolu_spawn_1",
                )
            ],
        ),
        NormalizedEvent(
            event_id="e3",
            timestamp="2026-08-06T10:02:00Z",
            source="tool",
            type="tool_output",
            content="Result line\n" * 20,  # 20 lines -> large output (>10 lines)
            meta={"tool_use_id": "toolu_spawn_1"},
        ),
    ]
    return NormalizedSession(
        session_id="session_r4_test",
        source_file=Path("session_r4_test.jsonl"),
        events=events,
        tokens_used=1200,
        cost_usd=0.012,
        subagents=[subagent1],
    )


def test_4_tier_output_artifacts_written(tmp_path: Path, sample_session_with_subagents: NormalizedSession) -> None:
    """Assert all 4 distinct text tiers plus JSON sidecar are generated by process_single_session."""
    processed = process_single_session(
        sample_session_with_subagents,
        tmp_path,
        DummySkipCache(),
        force=True,
    )
    assert processed is True

    written_files = {p.name for p in tmp_path.glob("transcripts/**/*")}
    assert any(name.endswith(".controller.md") for name in written_files)
    assert any(name.endswith(".full.md") for name in written_files)
    assert any(name.endswith(".md") and not name.endswith(".controller.md") and not name.endswith(".full.md") for name in written_files)
    assert any(name.endswith(".html") for name in written_files)
    assert any(name.endswith(".json") for name in written_files)

    controller_path = next(p for p in tmp_path.glob("transcripts/**/*.controller.md"))
    full_path = next(p for p in tmp_path.glob("transcripts/**/*.full.md"))
    concise_path = next(p for p in tmp_path.glob("transcripts/**/*.md") if not p.name.endswith(".controller.md") and not p.name.endswith(".full.md"))

    controller_content = controller_path.read_text(encoding="utf-8")
    full_content = full_path.read_text(encoding="utf-8")
    concise_content = concise_path.read_text(encoding="utf-8")

    # Controller has controlling agent events but NOT subagent conversation details
    assert "Controlling Agent Transcript" in controller_content
    assert "Analysis result for <dataset_table>" not in controller_content
    assert "## 🧵 Subagents" in controller_content

    # Full has full subagent transcript
    assert "Full Transcript" in full_content
    assert "## 🧵 Subagent Transcripts" in full_content
    assert "Analysis result for &lt;dataset_table&gt;" in full_content or "Analysis result for <dataset_table>" in full_content

    # Concise has summary index
    assert "Summary" in concise_content
    assert "## 📊 Event Index" in concise_content


def test_xml_html_tag_escaping(sample_session_with_subagents: NormalizedSession) -> None:
    """Assert XML/HTML tags in user prompt, thinking blocks, and tool outputs are safely escaped."""
    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        sample_session_with_subagents,
        "slug_test",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {"project": "aops"},
        None,
    )

    # In HTML, raw tags must be escaped as &lt; and &gt;
    assert "&lt;USER_REQUEST&gt;" in html
    assert "&lt;thinking_tag&gt;" in html
    assert "<script>" not in html

    # In Markdown, thinking blocks escape raw tags so viewers do not swallow them
    assert "&lt;thinking_tag&gt;" in controller_md or "`" in controller_md
    assert "&lt;USER_REQUEST&gt;" in controller_md


def test_escape_html_quotes() -> None:
    """Assert double quotes and single quotes are escaped by _escape_html."""
    raw = 'Hello "World" & \'Team\''
    escaped = _escape_html(raw)
    assert '&quot;' in escaped
    assert '&#x27;' in escaped
    assert '&amp;' in escaped
    assert '"' not in escaped
    assert "'" not in escaped
    assert escaped == 'Hello &quot;World&quot; &amp; &#x27;Team&#x27;'



def test_large_tool_output_collapsible_details(sample_session_with_subagents: NormalizedSession) -> None:
    """Assert large tool call outputs (>500 chars or >10 lines) are wrapped in <details><summary>Tool Output ({count} bytes)</summary>."""
    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        sample_session_with_subagents,
        "slug_test",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {"project": "aops"},
        None,
    )

    # The 20 lines tool output is large, so it must be wrapped in <details><summary>
    assert "<details><summary>Tool Output (" in controller_md
    assert "bytes)</summary>" in controller_md
    assert "<details class=\"tool-output-details\">" in html
    assert "<summary>Tool Output (" in html


def test_explicit_token_cost_breakdown_accounting(sample_session_with_subagents: NormalizedSession) -> None:
    """Assert token and cost accounting explicitly splits controller vs subagent tokens."""
    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        sample_session_with_subagents,
        "slug_test",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {"project": "aops"},
        None,
    )

    # Check frontmatter
    assert "controller_tokens: 1200" in controller_md
    assert "subagent_tokens: 400" in controller_md
    assert "total_tokens_used: 1600" in controller_md
    assert "controller_cost_usd: 0.012000" in controller_md
    assert "subagent_cost_usd: 0.004000" in controller_md
    assert "total_cost_usd: 0.016000" in controller_md

    # Check JSON sidecar
    assert json_sidecar["controller_tokens"] == 1200
    assert json_sidecar["subagent_tokens"] == 400
    assert json_sidecar["total_tokens_used"] == 1600
    assert json_sidecar["controller_cost_usd"] == 0.012
    assert json_sidecar["subagent_cost_usd"] == 0.004
    assert json_sidecar["total_cost_usd"] == 0.016


def test_sparse_step_index_no_degraded_warnings() -> None:
    """Assert sparse/non-contiguous step_index sequence IDs produce no degraded state warnings."""
    events = [
        NormalizedEvent(
            event_id="step_1",
            timestamp="2026-08-06T10:00:00Z",
            source="user",
            type="message",
            content="First prompt",
            meta={"step_index": 1},
        ),
        NormalizedEvent(
            event_id="step_15",
            timestamp="2026-08-06T10:01:00Z",
            source="model",
            type="message",
            content="Response after skipped step indices",
            meta={"step_index": 15},
        ),
        NormalizedEvent(
            event_id="step_102",
            timestamp="2026-08-06T10:02:00Z",
            source="tool",
            type="tool_output",
            content="Output at sparse index 102",
            meta={"step_index": 102},
        ),
    ]
    session = NormalizedSession(
        session_id="sparse_session",
        source_file=Path("sparse.jsonl"),
        events=events,
        degraded=[],
    )

    assert session.degraded == []
    json_sidecar = build_json_sidecar(
        session, "sparse", "2026-08-06T10:00:00Z", "2026-08-06T10:02:00Z", "2026-08-06T10:02:00Z", True, {}, None
    )
    assert json_sidecar["event_count"] == 3


def test_escape_html_non_string_inputs() -> None:
    """Assert _escape_html handles non-string types gracefully via str() conversion."""
    assert _escape_html(None) == "None"
    assert _escape_html(123) == "123"
    assert _escape_html(45.67) == "45.67"
    assert _escape_html(True) == "True"
    assert _escape_html(False) == "False"
    assert _escape_html(["<tag>", "'quote'"]) == "[&#x27;&lt;tag&gt;&#x27;, &quot;&#x27;quote&#x27;&quot;]"
    assert _escape_html({"a": "<b&c>"}) == "{&#x27;a&#x27;: &#x27;&lt;b&amp;c&gt;&#x27;}"


def test_escape_html_edge_cases_multiline_and_empty() -> None:
    """Assert _escape_html handles empty strings, whitespace, and multi-line content."""
    assert _escape_html("") == ""
    assert _escape_html("   ") == "   "
    assert _escape_html("\n\t") == "\n\t"

    multiline = "Line 1 <script>\nLine 2 \"quote\"\nLine 3 'single' & backslash \\"
    escaped = _escape_html(multiline)
    assert "Line 1 &lt;script&gt;\nLine 2 &quot;quote&quot;\nLine 3 &#x27;single&#x27; &amp; backslash \\" in escaped


def test_escape_html_attribute_context_breakout_prevention() -> None:
    """Assert _escape_html prevents HTML attribute breakouts when filenames/metadata contain quotes."""
    adversarial_base = 'file_name" onload="alert(1)" \'other\''
    escaped_base = _escape_html(adversarial_base)

    # Simulate HTML hyperlink generation as done in renderer
    html_link = f'<a href="./{escaped_base}.full.md">{escaped_base}.full.md</a>'

    assert 'file_name&quot; onload=&quot;alert(1)&quot; &#x27;other&#x27;' in html_link
    assert 'file_name" onload=' not in html_link
    assert "'other'" not in html_link


def test_adversarial_subagent_rendering() -> None:
    """Assert subagent metadata with HTML tags, quotes, and newlines renders safely."""
    subagent = SubagentTranscript(
        agent_id="sub_<1>",
        source_file=Path("agent-sub1.jsonl"),
        agent_type="analyst\"type",
        name="Analyst's Worker",
        description="Line1 <tag>\nLine2 \"quoted\" & 'single'",
        parent_tool_use_id="toolu_spawn_adv",
        tokens_used=100,
        cost_usd=0.001,
        spawn_depth=1,
        events=[
            NormalizedEvent(
                event_id="sub_e1",
                timestamp="2026-08-06T10:01:00Z",
                source="model",
                type="message",
                content="Result with <script>alert(1)</script>",
            )
        ],
    )
    session = NormalizedSession(
        session_id="session_adv_sub",
        source_file=Path("session.jsonl"),
        events=[],
        subagents=[subagent],
    )

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "adv_slug\"quote",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {"project": "proj\"name"},
        None,
    )

    # HTML table should escape subagent fields
    assert "analyst&quot;type" in html
    assert "Line1 &lt;tag&gt;\nLine2 &quot;quoted&quot; &amp; &#x27;single&#x27;" in html
    assert "<script>" not in html

    # JSON sidecar should retain raw values
    assert json_sidecar["subagents"][0]["agent_type"] == 'analyst"type'
    assert json_sidecar["subagents"][0]["description"] == "Line1 <tag>\nLine2 \"quoted\" & 'single'"


def test_adversarial_json_payloads_in_tool_calls() -> None:
    """Assert tool calls with JSON payloads containing HTML tags, quotes, and newlines render safely."""
    import json

    events = [
        NormalizedEvent(
            event_id="e_tc",
            timestamp="2026-08-06T10:00:00Z",
            source="model",
            type="message",
            content="Running tool call",
            tool_calls=[
                NormalizedToolCall(
                    name="ExecuteCode",
                    args={
                        "code": "<script>alert('xss')</script>\nhtml = \"</div>\"",
                        "flag": True,
                        "count": 42,
                    },
                    call_id="call_tc_1",
                )
            ],
        )
    ]
    session = NormalizedSession(
        session_id="session_tc",
        source_file=Path("tc.jsonl"),
        events=events,
    )

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "slug_tc",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {},
        None,
    )

    # In HTML, the tool call JSON representation must be HTML-escaped inside <code>
    assert "&lt;script&gt;alert(&#x27;xss&#x27;)&lt;/script&gt;" in html
    assert "&lt;/div&gt;" in html

    # Verify JSON sidecar serialises cleanly
    json_str = json.dumps(json_sidecar)
    parsed = json.loads(json_str)
    assert parsed["session_id"] == "session_tc"



def test_non_string_and_empty_event_content_rendering() -> None:
    """Assert events with non-string, empty, or list content render without raising exceptions."""
    events = [
        NormalizedEvent(
            event_id="e_list",
            timestamp="2026-08-06T10:00:00Z",
            source="model",
            type="message",
            content=["Item 1 <tag>", "Item 2 'quote'"],
        ),
        NormalizedEvent(
            event_id="e_none",
            timestamp="2026-08-06T10:01:00Z",
            source="model",
            type="message",
            content=None,
        ),
        NormalizedEvent(
            event_id="e_int",
            timestamp="2026-08-06T10:02:00Z",
            source="model",
            type="message",
            content=12345,
        ),
    ]
    session = NormalizedSession(
        session_id="session_non_str",
        source_file=Path("non_str.jsonl"),
        events=events,
    )

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "slug_non_str",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {},
        None,
    )

    # List content joined with newlines and escaped
    assert "Item 1 &lt;tag&gt;" in controller_md
    assert "12345" in controller_md
    assert "12345" in html


def test_adversarial_correlation_and_metadata_in_html() -> None:
    """Assert session metadata with HTML special characters is properly escaped in HTML tags and attributes."""
    session = NormalizedSession(
        session_id="sess_<script>alert('id')</script>",
        source_file=Path("session.jsonl"),
        events=[],
    )
    correlation = {
        "project": "proj\"onload=\"alert('proj')",
        "task_id": "task'<script>",
        "pr_number": "999\"bad",
    }

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "slug'<script>",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        correlation,
        "Insights with <tag> & 'quote'",
    )

    # Document title and H1 header
    assert "<title>Session sess_&lt;script&gt;alert(&#x27;id&#x27;)&lt;/script&gt;</title>" in html
    assert "<h1>Session sess_&lt;script&gt;alert(&#x27;id&#x27;)&lt;/script&gt;</h1>" in html

    # Meta-grid items
    assert "proj&quot;onload=&quot;alert(&#x27;proj&#x27;)" in html
    assert "task&#x27;&lt;script&gt;" in html
    assert "slug&#x27;&lt;script&gt;" in html

    # Insights block
    assert "Insights with &lt;tag&gt; &amp; &#x27;quote&#x27;" in html


def test_thinking_block_variations_and_multiline() -> None:
    """Assert thinking blocks with multi-line HTML tags, opaque thinking, or empty thinking render correctly."""
    events = [
        NormalizedEvent(
            event_id="e_think1",
            timestamp="2026-08-06T10:00:00Z",
            source="model",
            type="message",
            content="Done",
            thinking="Step 1: <analyze>\nStep 2: \"confirm\" & evaluate",
        ),
        NormalizedEvent(
            event_id="e_think2",
            timestamp="2026-08-06T10:01:00Z",
            source="model",
            type="message",
            content="Done 2",
            thinking_opaque=True,
        ),
    ]
    session = NormalizedSession(
        session_id="session_thinking",
        source_file=Path("thinking.jsonl"),
        events=events,
    )

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "slug_thinking",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {},
        None,
    )

    # Thinking tags escaped in MD and HTML
    assert "&lt;analyze&gt;" in controller_md
    assert "&quot;confirm&quot;" in html

    # Opaque thinking warning present
    assert "not recoverable — Claude Code returned this block empty" in controller_md
    assert "not recoverable — Claude Code returned this block empty" in html


def test_subagent_budget_overflow_stress() -> None:
    """Assert full markdown render truncates subagent transcripts when MAX_SUBAGENT_FULL_MD_CHARS budget is exceeded."""
    large_event_content = "X" * 3_000_000
    subagents = [
        SubagentTranscript(
            agent_id=f"sub_{i}",
            source_file=Path(f"sub_{i}.jsonl"),
            agent_type="worker",
            name=f"Worker {i}",
            description=f"Subagent {i}",
            parent_tool_use_id=f"toolu_{i}",
            tokens_used=1000,
            cost_usd=0.01,
            spawn_depth=1,
            events=[
                NormalizedEvent(
                    event_id=f"e_{i}",
                    timestamp="2026-08-06T10:00:00Z",
                    source="model",
                    type="message",
                    content=large_event_content,
                )
            ],
        )
        for i in range(4)
    ]

    session = NormalizedSession(
        session_id="session_budget",
        source_file=Path("budget.jsonl"),
        events=[],
        subagents=subagents,
    )

    controller_md, full_md, concise_md, html, json_sidecar = render_session_to_all_formats(
        session,
        "slug_budget",
        "2026-08-06T10:00:00Z",
        "2026-08-06T10:02:00Z",
        "2026-08-06T10:02:00Z",
        True,
        {},
        None,
    )

    # Full MD must contain budget warning
    assert "Size budget of 8000000 characters reached" in full_md
    assert "subagent transcript(s) totalling" in full_md

