#!/usr/bin/env python3
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

# Add aops-core to path
SCRIPT_DIR = Path(__file__).parent.resolve()
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(REPO_ROOT / "aops-core"))


def generate_pr_body(task: Any) -> str:
    """Generate a Pull Request body from a Task object.

    Extracts the description and acceptance criteria from the task body.
    Converts acceptance criteria to GitHub checklist format.
    """
    body = task.body

    # Remove "Relationships" section (standard clean up)
    # Regex: matches optional newlines, header, content, until next header or end
    body = re.sub(r"\n*## Relationships\n[\s\S]*?(?=\n\n## |\Z)", "", body)

    # Remove Title Header if present (usually the first line)
    # Match "# Title" at start of string
    title_pattern = re.compile(f"^# {re.escape(task.title)}\\s*\n", re.MULTILINE)
    body = title_pattern.sub("", body)

    # Logic to find Acceptance Criteria
    # We look for a header "## Acceptance Criteria" (case insensitive)
    ac_match = re.search(
        r"(?i)^##\s+Acceptance Criteria\s*\n(.*?)(?=\n^## |\Z)",
        body,
        re.MULTILINE | re.DOTALL,
    )

    acceptance_criteria = []
    description = body

    if ac_match:
        ac_text = ac_match.group(1)
        # Remove the AC section from the description
        description = body.replace(ac_match.group(0), "").strip()

        # Process AC text
        for line in ac_text.splitlines():
            line = line.strip()
            # Convert any list item with checkbox to standard "- [ ]"
            if re.match(r"^[-*]\s*\[[ xX]\]", line):
                # Force unchecked for PR
                clean_line = re.sub(r"^[-*]\s*\[[ xX]\]", "- [ ]", line)
                acceptance_criteria.append(clean_line)
            elif line:
                acceptance_criteria.append(line)
    else:
        # Fallback: Find ANY checkboxes in the body if no AC header exists
        checklist_items = re.findall(r"^[-*]\s*\[[ xX]\].*$", body, re.MULTILINE)
        if checklist_items:
            # We do NOT remove them from description here
            description = body.strip()

            # Add them to AC list
            for item in checklist_items:
                acceptance_criteria.append(re.sub(r"^[-*]\s*\[[ xX]\]", "- [ ]", item))

    # Construct the PR Body
    parts = []

    if description:
        parts.append(description)
        parts.append("\n")

    if acceptance_criteria:
        parts.append("## Acceptance Criteria")
        parts.append("\n".join(acceptance_criteria))
        parts.append("\n")

    # Footer
    parts.append("---")
    parts.append(f"Closes {task.id}")
    parts.append(f"*Generated by Polecat for task {task.id}*")

    return "\n".join(parts)


def check_gh_installed() -> bool:
    """Check if GitHub CLI (gh) is installed and authenticated."""
    try:
        subprocess.run(["gh", "--version"], check=True, capture_output=True)
        # Check auth status
        result = subprocess.run(["gh", "auth", "status"], capture_output=True)
        return result.returncode == 0
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def get_pr_status(pr_ref: str, repo_path: Path | None = None) -> dict[str, Any] | None:
    """Get PR status using gh CLI.

    Args:
        pr_ref: PR number or URL
        repo_path: Optional path to run command in

    Returns:
        Dict with PR info (state, mergedAt, reviews, updatedAt) or None if failed
    """
    try:
        # We want: state, mergedAt, reviews, updatedAt
        # reviews contains: author, state, submittedAt, body
        cmd = [
            "gh",
            "pr",
            "view",
            pr_ref,
            "--json",
            "state,mergedAt,reviews,updatedAt,url,number,title",
        ]
        result = subprocess.run(
            cmd,
            cwd=repo_path,
            capture_output=True,
            text=True,
            timeout=15,
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
    except (
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
        json.JSONDecodeError,
        FileNotFoundError,
    ):
        pass
    return None
