#!/usr/bin/env bash
# Install the pre-commit secret-linter backstop (Layer 2) in the sessions repo.
#
# Run once after initial sessions-repo setup, or after moving the aops-core checkout.
# The generated .pre-commit-config.yaml bakes in the absolute path to the scanner
# so pre-commit can find it without AOPS_CORE being set at hook-run time.
#
# Requires:
#   $AOPS_SESSIONS  — sessions git repo (falls back to $POLECAT_HOME/sessions)
#   $AOPS_CORE      — aops-core checkout (defaults to this script's parent directory)
#   pre-commit      — on $PATH (install via: uv tool install pre-commit)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AOPS_CORE="${AOPS_CORE:-"$(cd "$SCRIPT_DIR/.." && pwd)"}"

if [[ -n "${AOPS_SESSIONS:-}" ]]; then
    SESSIONS_REPO="$AOPS_SESSIONS"
elif [[ -n "${POLECAT_HOME:-}" ]]; then
    SESSIONS_REPO="$POLECAT_HOME/sessions"
else
    echo "Error: set \$AOPS_SESSIONS (or \$POLECAT_HOME) before running this script." >&2
    exit 1
fi

SCANNER="$AOPS_CORE/scripts/check_transcript_secrets.py"

if [[ ! -f "$SCANNER" ]]; then
    echo "Error: scanner not found at $SCANNER" >&2
    exit 1
fi

if [[ ! -d "$SESSIONS_REPO/.git" ]]; then
    echo "Error: $SESSIONS_REPO is not a git repository" >&2
    exit 1
fi

CONFIG="$SESSIONS_REPO/.pre-commit-config.yaml"

cat > "$CONFIG" << YAML
# Generated by install_sessions_hooks.sh — re-run to update after moving aops-core.
# Layer 2 backstop: blocks commits that carry a secret into the sessions corpus.
# The scanner (check_transcript_secrets.py) imports lib/secret_redaction.py so
# Layers 1 and 2 share one pattern source — edit patterns there, not here.

repos:
  - repo: local
    hooks:
      - id: check-transcript-secrets
        name: block secrets in transcripts/summaries
        entry: python $SCANNER
        language: system
        pass_filenames: true
        files: '^(transcripts|summaries|subagent-transcripts|subagent-summaries)/.*\.(md|json)\$'
        stages: [pre-commit]
YAML

echo "Wrote $CONFIG"

if command -v pre-commit &>/dev/null; then
    cd "$SESSIONS_REPO"
    pre-commit install
    echo "pre-commit hook installed in $SESSIONS_REPO"
else
    echo "Error: pre-commit not on PATH — install it first:" >&2
    echo "  uv tool install pre-commit && cd $SESSIONS_REPO && pre-commit install" >&2
    exit 1
fi
