# Batch Processing Workflow - Constraint Format
# Converted from: workflows/batch-processing.md
# Conversion date: 2026-01-23

workflow: batch-processing
description: Multiple similar items processed in parallel
extends: [base-task-tracking]

context:
  applies_when:
    - "process all X", "batch update"
    - multiple independent tasks
    - items don't share mutable state
  not_when:
    - items have dependencies (process sequentially)
    - shared state (conflicts likely)
    - single item (use minor-edit or design)

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # PRECONDITIONS
  # ---------------------------------------------------------------------------

  # Must validate task independence before parallel processing
  - BEFORE spawn_workers: task_independence_validated

  # Must verify no file conflicts
  - BEFORE spawn_workers: no_file_conflicts

  # ---------------------------------------------------------------------------
  # PROCESSING RULES
  # ---------------------------------------------------------------------------

  # Workers commit locally, supervisor pushes
  - ALWAYS: workers_commit_locally
  - ALWAYS: supervisor_pushes

  # Smart subagent, dumb supervisor
  - ALWAYS: smart_subagent_dumb_supervisor

  # ---------------------------------------------------------------------------
  # WORKER SELECTION
  # ---------------------------------------------------------------------------

  # Use hypervisor for 5+ items
  - IF item_count_gte_5 THEN use_hypervisor

  # Use direct spawning for 2-4 items
  - IF item_count_2_to_4 THEN use_direct_spawn

  # ---------------------------------------------------------------------------
  # PROHIBITIONS
  # ---------------------------------------------------------------------------

  - NEVER: parallel_process_dependent_tasks
  - NEVER: parallel_modify_shared_state

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  - ON batch_request: INVOKE validate_independence
  - ON independence_confirmed: INVOKE spawn_workers
  - ON all_workers_complete: INVOKE supervisor_push

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  task_independence_validated:
    check: all items can be processed without affecting each other

  no_file_conflicts:
    check: no two tasks modify the same file

  workers_commit_locally:
    check: each worker commits its own changes

  supervisor_pushes:
    check: supervisor aggregates and pushes after workers complete

  smart_subagent_dumb_supervisor:
    check: |
      supervisor writes ONE smart prompt;
      worker discovers, processes, reports autonomously

  item_count_gte_5:
    check: batch contains 5 or more items

  item_count_2_to_4:
    check: batch contains 2-4 items

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - Task independence requirement
# - Worker selection by count (hypervisor vs direct)
# - Smart subagent, dumb supervisor principle
# - Workers commit, supervisor pushes

# What was clarified:
# - Independence validation is explicit precondition
# - Worker selection is conditional on item count
