# Debugging Workflow - Constraint Format
# Converted from: workflows/debugging.md
# Conversion date: 2026-01-23

workflow: debugging
description: Understand the problem before fixing it
extends: [base-task-tracking, base-verification]

context:
  applies_when:
    - "why doesn't this work?"
    - investigating unexpected behavior
    - bug where cause is unknown
  not_when:
    - cause already known (use minor-edit or design)

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # INVESTIGATION SEQUENCING
  # ---------------------------------------------------------------------------

  # Must define success criteria before investigation
  - BEFORE investigate: success_criteria_defined

  # Must create reproducing test before fixing
  - BEFORE fix: reproducing_test_exists

  # Must document findings before routing to fix workflow
  - BEFORE route_to_fix: findings_documented

  # ---------------------------------------------------------------------------
  # POSTCONDITIONS
  # ---------------------------------------------------------------------------

  # After investigation, document root cause in task
  - AFTER investigate: root_cause_documented

  # ---------------------------------------------------------------------------
  # EXIT ROUTING
  # ---------------------------------------------------------------------------

  # Must route to appropriate fix workflow after debugging
  - IF simple_fix THEN route_to minor-edit
  - IF complex_fix THEN route_to design
  - IF unclear_fix THEN ask_user

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  - ON bug_reported: INVOKE define_success_criteria
  - ON success_criteria_defined: INVOKE create_reproducing_test
  - ON test_reproduces_bug: INVOKE investigate
  - ON root_cause_found: INVOKE document_findings
  - ON findings_documented: INVOKE route_to_fix_workflow

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  success_criteria_defined:
    check: task.body contains "## Success Criteria" OR explicit "fixed means X"

  reproducing_test_exists:
    check: test exists that fails now but will pass when fixed

  findings_documented:
    check: task.body contains root cause analysis

  root_cause_documented:
    check: task.body contains "## Root Cause" OR explicit cause statement

  simple_fix:
    check: fix is single-file, obvious change

  complex_fix:
    check: fix requires multiple files OR design decisions

  unclear_fix:
    check: NOT simple_fix AND NOT complex_fix

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - "Understand before fixing" principle
# - Success criteria first
# - Reproducing test requirement
# - Document findings in task
# - Exit routing to appropriate workflow

# What was clarified:
# - Investigation sequence is explicit (criteria → test → investigate → document → route)
# - Exit routing conditions are concrete predicates
