# Feature Development Workflow - Constraint Format
# Converted from: aops-core/skills/framework/workflows/05-feature-development.md
# Conversion date: 2026-01-23

workflow: feature-dev
description: Test-first feature development from idea to validated implementation

context:
  applies_when:
    - adding new features
    - building significant functionality
    - implementing user-requested capabilities
  not_when:
    - bug fixes (unless requiring new functionality)
    - simple refactoring
    - documentation-only changes

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # PHASE SEQUENCING (Preconditions)
  # ---------------------------------------------------------------------------

  # Phase 1→2: Requirements need captured story
  - BEFORE analyze_requirements: user_story_captured

  # Phase 2→3: Experiment design needs clear requirements
  - BEFORE design_experiment: requirements_documented
  - BEFORE design_experiment: success_criteria_defined

  # Phase 3→4: Test writing needs experiment plan
  - BEFORE write_tests: experiment_plan_exists

  # Phase 4→5: Dev planning needs failing tests
  - BEFORE plan_development: tests_exist
  - BEFORE plan_development: tests_fail

  # Phase 5→6: Execution needs approved plan
  - BEFORE implement: plan_approved
  - BEFORE implement: tests_exist

  # Phase 6→7: Validation needs implementation complete
  - BEFORE validate: implementation_complete

  # Phase 7→8: Spec synthesis needs validation pass
  - BEFORE synthesize_spec: validation_passed
  - BEFORE synthesize_spec: critic_reviewed

  # ---------------------------------------------------------------------------
  # COMMIT GATES (Strict Preconditions)
  # ---------------------------------------------------------------------------

  - BEFORE commit: tests_pass
  - BEFORE commit: critic_reviewed
  - BEFORE commit: no_regressions

  # ---------------------------------------------------------------------------
  # POSTCONDITIONS
  # ---------------------------------------------------------------------------

  - AFTER implement_step: run_tests
  - AFTER implement_step: update_todo_progress
  - AFTER validate_success: commit_feature
  - AFTER validate_failure: revert_feature
  - AFTER complete: update_spec
  - AFTER complete: close_experiment_task

  # ---------------------------------------------------------------------------
  # INVARIANTS (Always True)
  # ---------------------------------------------------------------------------

  - ALWAYS: one_task_in_progress
  - ALWAYS: changes_tracked_in_task
  - ALWAYS: documentation_integrity
  - ALWAYS: single_source_of_truth

  # ---------------------------------------------------------------------------
  # PROHIBITIONS (Never Allowed)
  # ---------------------------------------------------------------------------

  - NEVER: commit_with_failing_tests
  - NEVER: implement_without_plan
  - NEVER: implement_without_tests
  - NEVER: skip_critic_review
  - NEVER: ship_partial_success
  - NEVER: work_around_blockers
  - NEVER: rationalize_test_failure
  - NEVER: duplicate_documentation

  # ---------------------------------------------------------------------------
  # CONDITIONALS (Context-Dependent)
  # ---------------------------------------------------------------------------

  - IF tests_fail THEN halt_and_fix_or_revert
  - IF blocked_on_infrastructure THEN halt_and_report
  - IF requirements_unclear THEN return_to_analysis
  - IF framework_feature THEN use_detailed_critic
  - IF routine_feature THEN use_fast_critic
  - IF iteration_fails THEN revert
  - IF ambiguous_requirements THEN fail_fast

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  # Phase transitions
  - ON user_story_captured: INVOKE analyze_requirements
  - ON requirements_documented: INVOKE design_experiment
  - ON experiment_plan_exists: INVOKE write_tests
  - ON tests_fail: INVOKE plan_development
  - ON plan_approved: INVOKE implement
  - ON implementation_complete: INVOKE validate
  - ON validation_passed: INVOKE synthesize_spec

  # Review gates
  - ON plan_ready: INVOKE plan-agent
  - ON review_needed: INVOKE critic
  - ON critic_escalate: INVOKE detailed_critic

  # Error handling
  - ON tests_fail_unexpected: INVOKE halt
  - ON blocked: INVOKE halt_and_report
  - ON validation_failed: INVOKE revert_or_iterate

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  # Phase completion checks
  user_story_captured:
    check: task.body contains "## User Story" OR file exists with user-story content

  requirements_documented:
    check: task.body contains "## Requirements"

  success_criteria_defined:
    check: task.body contains "## Success Criteria"

  experiment_plan_exists:
    check: task with tag "experiment" exists for this feature

  tests_exist:
    check: grep for "def test_" OR "test(" in relevant test files

  tests_fail:
    check: pytest exit code != 0 for feature tests

  tests_pass:
    check: pytest exit code == 0 for all tests

  plan_approved:
    check: task.body contains "## Approved Plan" OR user said "approved" OR "lgtm"

  implementation_complete:
    check: all TodoWrite items for implementation marked completed

  critic_reviewed:
    check: critic agent spawned AND returned verdict

  no_regressions:
    check: full test suite passes (not just feature tests)

  validation_passed:
    check: all success criteria met AND tests pass AND critic approved

  # Condition checks
  framework_feature:
    check: files touched include "aops-core/" OR tags include "framework"

  routine_feature:
    check: NOT framework_feature

  blocked_on_infrastructure:
    check: error indicates missing tool/service/permission

  requirements_unclear:
    check: user asks clarifying question OR requirements conflict

  iteration_fails:
    check: second validation attempt fails

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - All 8 phases mapped to constraint chains
# - Mandatory critic review before commit
# - Test-first requirement (tests must exist AND fail before implementation)
# - Fail-fast behavior (halt on test failure, revert on validation failure)
# - Plan-first requirement
# - Single source of truth principle
# - ADHD accommodations (TodoWrite tracking maintained)

# What was clarified by logical expression:
# - Phase dependencies now explicit (BEFORE/AFTER chains)
# - The "no partial success" rule now has concrete prohibition (NEVER ship_partial_success)
# - Iteration limit (max 1) expressed as conditional: IF iteration_fails THEN revert
# - Critic review timing is explicit: BEFORE commit, not just "Phase 7"

# Patterns discovered:
# - Multi-phase workflows become chains of BEFORE constraints
# - "Don't skip steps" becomes explicit predicates + NEVER prohibitions
# - "Optional for X" conditions map to IF-THEN rules
# - Fail-fast behavior = NEVER + ON-INVOKE halt patterns
