# Minor Edit Workflow - Constraint Format
# Converted from: workflows/minor-edit.md
# Conversion date: 2026-01-23

workflow: minor-edit
description: Small, focused change - single file, obvious fix
extends: [base-task-tracking, base-tdd, base-verification, base-commit]

context:
  applies_when:
    - typo fixes, small bug fixes, minor refactoring
    - documentation updates, config changes
    - "quick change", "simple fix"
  not_when:
    - multiple files involved (use design)
    - architectural decisions needed (use design)
    - complex logic required (use design)

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # SCOPE LIMITS
  # ---------------------------------------------------------------------------

  # Must be single-file scope
  - ALWAYS: single_file_scope

  # Must be obvious fix (no design decisions)
  - ALWAYS: obvious_fix

  # ---------------------------------------------------------------------------
  # UPGRADE TRIGGERS
  # ---------------------------------------------------------------------------

  # If complexity discovered during implementation, stop and upgrade
  - IF complexity_discovered THEN halt_and_upgrade_to_design

  # ---------------------------------------------------------------------------
  # INHERITED CONSTRAINTS
  # ---------------------------------------------------------------------------
  # All constraints from base workflows apply:
  # - base-task-tracking: task management
  # - base-tdd: test-first when applicable
  # - base-verification: verify before commit
  # - base-commit: commit workflow

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  - ON multiple_files_needed: UPGRADE_TO design
  - ON design_decision_needed: UPGRADE_TO design
  - ON edge_case_discovered: UPGRADE_TO design

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  single_file_scope:
    check: changes affect exactly 1 file

  obvious_fix:
    check: no design decisions required, fix is self-evident

  complexity_discovered:
    check: |
      multiple_files_needed OR
      design_decision_needed OR
      edge_case_discovered

  multiple_files_needed:
    check: implementation requires modifying more than 1 file

  design_decision_needed:
    check: choice between approaches with tradeoffs

  edge_case_discovered:
    check: found scenario not covered by original scope

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - Single file, obvious fix scope
# - Upgrade signal when complexity discovered
# - Base workflow inheritance

# What was clarified:
# - "Simple" defined via predicates (single file, obvious fix)
# - Upgrade triggers are explicit conditions, not judgment calls
