# QA Demo Workflow - Constraint Format
# Converted from: workflows/qa-demo.md
# Conversion date: 2026-01-23

workflow: qa-demo
description: Independent verification before completion - "does it run without error?"

context:
  applies_when:
    - feature complete, tests pass, before final commit
    - user-facing functionality changes
    - complex changes with multiple acceptance criteria
  not_when:
    - trivial changes (typo fixes)
    - already reviewed by user
    - integration validation needed (use prove-feature)

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # PRECONDITIONS
  # ---------------------------------------------------------------------------

  # Feature must be complete before QA
  - BEFORE qa_verification: feature_complete

  # Tests must pass before QA
  - BEFORE qa_verification: tests_pass

  # ---------------------------------------------------------------------------
  # QA GATE
  # ---------------------------------------------------------------------------

  # QA must verify before completion
  - BEFORE complete: qa_verified

  # ---------------------------------------------------------------------------
  # VERDICT HANDLING
  # ---------------------------------------------------------------------------

  - IF qa_verified THEN proceed_to_completion
  - IF qa_issues_found THEN fix_and_reverify

  # ---------------------------------------------------------------------------
  # PROHIBITIONS
  # ---------------------------------------------------------------------------

  - NEVER: complete_without_qa
  - NEVER: ignore_qa_issues

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  - ON feature_ready: INVOKE qa_agent
  - ON qa_verified: PROCEED_TO complete
  - ON qa_issues: INVOKE fix_issues

# ============================================================================
# INVOCATION
# ============================================================================

qa_invocation:
  agent: qa
  prompt_template: |
    Verify work meets acceptance criteria: [CRITERIA].
    Check functionality, quality, completeness.

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  feature_complete:
    check: all implementation tasks marked done

  tests_pass:
    check: pytest exit code == 0

  qa_verified:
    check: qa agent returned "VERIFIED"

  qa_issues_found:
    check: qa agent returned "ISSUES" with critical/major items

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - QA as independent verification gate
# - Verdicts: VERIFIED (proceed) vs ISSUES (fix)
# - Timing: after tests pass, before completion

# What was clarified:
# - QA invocation template is explicit
# - Verdict handling is conditional rules
