# TDD Cycle Workflow - Constraint Format
# Converted from: workflows/tdd-cycle.md + workflows/base-tdd.md
# Conversion date: 2026-01-23

workflow: tdd-cycle
description: Red-green-refactor cycle for any testable code change

context:
  applies_when:
    - implementing new features
    - fixing bugs (reproduce with test first)
    - refactoring existing code
  not_when:
    - non-code changes (docs, config)
    - exploratory work where tests aren't yet meaningful
    - test infrastructure itself

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # RED PHASE (Test First)
  # ---------------------------------------------------------------------------

  # Must write test before implementation
  - BEFORE implement: test_exists

  # Test must fail before implementation (proves test is meaningful)
  - BEFORE implement: test_fails

  # Test must target ONE behavior (not multiple)
  - ALWAYS: test_targets_one_behavior

  # ---------------------------------------------------------------------------
  # GREEN PHASE (Minimal Implementation)
  # ---------------------------------------------------------------------------

  # After implementation, must run test
  - AFTER implement: run_test

  # Implementation should be minimal (just enough to pass)
  - ALWAYS: implementation_minimal

  # ---------------------------------------------------------------------------
  # REFACTOR PHASE
  # ---------------------------------------------------------------------------

  # Tests must still pass after refactoring
  - AFTER refactor: tests_still_pass

  # Can only refactor when tests are green
  - BEFORE refactor: tests_pass

  # ---------------------------------------------------------------------------
  # COMMIT GATES
  # ---------------------------------------------------------------------------

  # Cannot commit while tests fail
  - BEFORE commit: tests_pass

  # Cannot commit failing test without implementation (incomplete cycle)
  - NEVER: commit_failing_test_alone

  # ---------------------------------------------------------------------------
  # CYCLE ITERATION
  # ---------------------------------------------------------------------------

  # If more acceptance criteria remain, repeat cycle
  - IF acceptance_criteria_remain THEN start_new_cycle

  # ---------------------------------------------------------------------------
  # INVARIANTS
  # ---------------------------------------------------------------------------

  - ALWAYS: one_behavior_per_cycle
  - ALWAYS: test_before_code

  # ---------------------------------------------------------------------------
  # PROHIBITIONS
  # ---------------------------------------------------------------------------

  - NEVER: implement_before_test
  - NEVER: commit_failing_test
  - NEVER: skip_failure_verification
  - NEVER: implement_beyond_minimal

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  # Cycle state transitions
  - ON test_written: INVOKE verify_failure
  - ON test_fails: PROCEED_TO implement
  - ON test_passes: PROCEED_TO refactor_or_commit
  - ON refactor_complete: INVOKE verify_tests_pass
  - ON tests_pass AND acceptance_criteria_remain: INVOKE start_new_cycle
  - ON tests_pass AND acceptance_complete: PROCEED_TO commit

  # Error handling
  - ON test_passes_unexpectedly: HALT "test may not be testing what you think"
  - ON tests_fail_after_refactor: INVOKE undo_refactor

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  test_exists:
    check: file contains "def test_" OR "test(" for target behavior

  test_fails:
    check: pytest/test runner exit code != 0 for specific test

  test_passes:
    check: pytest/test runner exit code == 0 for specific test

  tests_pass:
    check: pytest/test runner exit code == 0 for all tests in scope

  tests_still_pass:
    check: tests_pass AND no new failures introduced

  test_targets_one_behavior:
    check: test function has single assertion focus (heuristic)

  implementation_minimal:
    check: implementation addresses only what test requires (heuristic, reviewer judgment)

  acceptance_criteria_remain:
    check: TodoWrite has uncompleted acceptance criteria items

  acceptance_complete:
    check: all acceptance criteria marked completed

  refactor_complete:
    check: cleanup changes committed OR explicitly skipped

# ============================================================================
# STATE MACHINE
# ============================================================================

# The TDD cycle is a tight loop with clear state transitions:
#
#   [RED]
#     │ write failing test
#     ▼
#   verify_failure ──(passes unexpectedly)──► HALT
#     │ (fails as expected)
#     ▼
#   [GREEN]
#     │ minimal implementation
#     ▼
#   verify_pass ──(still fails)──► continue implementing
#     │ (passes)
#     ▼
#   [REFACTOR] (optional)
#     │ cleanup
#     ▼
#   verify_still_pass ──(fails)──► undo refactor
#     │ (passes)
#     ▼
#   [COMMIT or REPEAT]
#     │
#     ├──(criteria remain)──► [RED]
#     └──(criteria complete)──► DONE

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - Core red-green-refactor pattern
# - "ONE behavior" per cycle requirement
# - Failure verification step (proves test works)
# - Optional refactor phase
# - Repeat until acceptance complete

# What was clarified by logical expression:
# - The "verify failure" step is now an explicit constraint with halt on unexpected pass
# - "Minimal implementation" is now an invariant (though still requires judgment)
# - The relationship between cycle completion and acceptance criteria is explicit
# - Refactor requires tests to be green first (implicit before, explicit now)

# Patterns discovered:
# - Tight loops map well to state machines with clear transitions
# - "Verify X" steps become (check + unexpected result → HALT) patterns
# - "Optional" phases still need BEFORE constraints to define valid entry
# - Iteration patterns need explicit "remain" predicates
