# Triage Email Workflow - Constraint Format
# Converted from: workflows/triage-email.md
# Conversion date: 2026-01-23

workflow: triage-email
description: Classify emails into actionable categories

context:
  applies_when:
    - processing incoming emails
    - email inbox triage
  not_when:
    - non-email content

# ============================================================================
# CONSTRAINTS
# ============================================================================

constraints:
  # ---------------------------------------------------------------------------
  # CRITICAL PRECONDITION
  # ---------------------------------------------------------------------------

  # Must check sent mail before classifying
  - BEFORE classify: sent_mail_checked

  # If matching reply exists, classify as Skip
  - IF reply_exists THEN classify_as_skip

  # ---------------------------------------------------------------------------
  # CLASSIFICATION RULES
  # ---------------------------------------------------------------------------

  # Exactly one classification per email
  - ALWAYS: one_classification_per_email

  # ---------------------------------------------------------------------------
  # CATEGORY CONDITIONS
  # ---------------------------------------------------------------------------

  # Task: actionable items
  - IF actionable_signals THEN classify_as_task

  # FYI: informational outcomes
  - IF informational_signals THEN classify_as_fyi

  # Skip: no action needed
  - IF skip_signals THEN classify_as_skip

  # Uncertain: mixed/unclear
  - IF uncertain_signals THEN ask_user

# ============================================================================
# CLASSIFICATION TABLE
# ============================================================================

classifications:
  task:
    action: create task
    signals:
      - "please review..."
      - decisions needed
      - deadlines
      - personal invitations

  fyi:
    action: archive
    signals:
      - "awarded", "approved"
      - outcomes
      - thank-you

  skip:
    action: archive
    signals:
      - noreply@
      - newsletters
      - already replied

  uncertain:
    action: ask user
    signals:
      - mixed signals
      - unknown sender

# ============================================================================
# PRIORITY INFERENCE (for Tasks)
# ============================================================================

priority_rules:
  p0:
    signals: ["URGENT", deadline <48h]
  p1:
    signals: [deadline <1 week, collaborator requests]
  p2:
    signals: [deadline <2 weeks, general]
  p3:
    signals: [no deadline, administrative]

# ============================================================================
# TRIGGERS
# ============================================================================

triggers:
  - ON email_received: INVOKE check_sent_mail
  - ON no_reply_exists: INVOKE classify_email
  - ON reply_exists: INVOKE archive_as_skip
  - ON classified_as_task: INVOKE create_task_with_priority
  - ON classified_as_fyi: INVOKE archive
  - ON classified_as_uncertain: INVOKE ask_user

# ============================================================================
# PREDICATES
# ============================================================================

predicates:
  sent_mail_checked:
    check: sent folder searched for matching reply

  reply_exists:
    check: sent mail contains reply to this email

  actionable_signals:
    check: |
      contains "please review" OR
      contains decision request OR
      contains deadline OR
      personal invitation

  informational_signals:
    check: |
      contains "awarded" OR "approved" OR
      outcome notification OR
      thank-you message

  skip_signals:
    check: |
      from noreply@ OR
      newsletter OR
      reply_exists

  uncertain_signals:
    check: |
      NOT actionable_signals AND
      NOT informational_signals AND
      NOT skip_signals

  one_classification_per_email:
    check: email receives exactly one category

# ============================================================================
# CONVERSION NOTES
# ============================================================================

# What was preserved:
# - Classification categories (Task, FYI, Skip, Uncertain)
# - Critical check: sent mail before classifying
# - Priority inference rules for tasks
# - Action per category

# What was clarified:
# - Sent mail check is explicit precondition
# - Classification signals are structured
# - One classification per email is invariant
