import re
from types import SimpleNamespace


def generate_pr_body(task) -> str:
    """Inlined from polecat/cli.py _generate_pr_body for testability."""
    body = task.body
    body = re.sub(r"\n*## Relationships\n[\s\S]*?(?=\n\n## |\Z)", "", body)
    title_pattern = re.compile(f"^# {re.escape(task.title)}\\s*\n", re.MULTILINE)
    body = title_pattern.sub("", body)
    ac_match = re.search(
        r"(?i)^##\s+Acceptance Criteria\s*\n(.*?)(?=\n^## |\Z)",
        body,
        re.MULTILINE | re.DOTALL,
    )
    acceptance_criteria = []
    description = body
    if ac_match:
        ac_text = ac_match.group(1)
        description = body.replace(ac_match.group(0), "").strip()
        for line in ac_text.splitlines():
            line = line.strip()
            if re.match(r"^[-*]\s*\[[ xX]\]", line):
                acceptance_criteria.append(re.sub(r"^[-*]\s*\[[ xX]\]", "- [ ]", line))
            elif line:
                acceptance_criteria.append(line)
    else:
        checklist_items = re.findall(r"^[-*]\s*\[[ xX]\].*$", body, re.MULTILINE)
        if checklist_items:
            description = body.strip()
            for item in checklist_items:
                acceptance_criteria.append(re.sub(r"^[-*]\s*\[[ xX]\]", "- [ ]", item))
    parts = []
    if description:
        parts.append(description)
        parts.append("\n")
    if acceptance_criteria:
        parts.append("## Acceptance Criteria")
        parts.append("\n".join(acceptance_criteria))
        parts.append("\n")
    parts.append("---")
    parts.append(f"Closes {task.id}")
    parts.append(f"*Generated by Polecat for task {task.id}*")
    return "\n".join(parts)


# Mock Task object
def mock_task(id="task-1", title="My Task", body=""):
    return SimpleNamespace(id=id, title=title, body=body)


def test_generate_pr_body_standard():
    body = """# My Task

This is the description.

## Acceptance Criteria
- [ ] Do thing A
- [ ] Do thing B
"""
    task = mock_task(body=body)
    pr_body = generate_pr_body(task)

    assert "This is the description." in pr_body
    assert "# My Task" not in pr_body  # Title removed from body (handled by PR title)
    assert "## Acceptance Criteria" in pr_body
    assert "- [ ] Do thing A" in pr_body
    assert "Closes task-1" in pr_body


def test_generate_pr_body_implicit_checklist():
    body = """# My Task

Description here.
- [ ] Item 1
- [ ] Item 2
"""
    task = mock_task(body=body)
    pr_body = generate_pr_body(task)

    # Description should still contain the items in implicit mode (context preservation)
    assert "Description here." in pr_body

    # But we also add an explicit AC section
    assert "## Acceptance Criteria" in pr_body
    assert "- [ ] Item 1" in pr_body


def test_generate_pr_body_relationships_stripped():
    body = """# My Task

Description.

## Relationships
- [parent] [[other-task]]

## Acceptance Criteria
- [ ] Check me
"""
    task = mock_task(body=body)
    pr_body = generate_pr_body(task)

    assert "Description." in pr_body
    assert "## Relationships" not in pr_body
    assert "## Acceptance Criteria" in pr_body
    assert "- [ ] Check me" in pr_body


def test_generate_pr_body_checked_items_become_unchecked():
    body = """# My Task

## Acceptance Criteria
- [x] Already done (maybe via decomposition)
"""
    task = mock_task(body=body)
    pr_body = generate_pr_body(task)

    assert "- [ ] Already done" in pr_body
    assert "- [x]" not in pr_body
