"""
Test custodiet's ability to detect axiom/heuristic violations.

This test demonstrates:
1. Custodiet is invoked during normal operation (via hook)
2. Custodiet checks axioms and heuristics
3. Custodiet can detect compliance issues

Tests use real audit context files generated by the custodiet_gate hook.
"""

from pathlib import Path

import pytest

from hooks.custodiet_gate import (
    increment_tool_count,
    load_custodiet_state,
    reset_compliance_state,
)


class TestCustodietInvocation:
    """CLAIM 1: Custodiet is invoked during normal operation."""

    def test_custodiet_gate_hook_increments_tool_count(self, tmp_path):
        """Verify custodiet hook tracks tool calls."""
        cwd = str(tmp_path)

        # Simulate 3 tool calls
        count1 = increment_tool_count(cwd)
        count2 = increment_tool_count(cwd)
        count3 = increment_tool_count(cwd)

        # State should show progressive counts
        assert count1 == 1
        assert count2 == 2
        assert count3 == 3

        # Verify state persists
        state = load_custodiet_state(cwd)
        assert state is not None
        assert state["tool_calls_since_compliance"] == 3

    def test_custodiet_gate_hook_triggers_at_threshold(self, tmp_path):
        """Verify custodiet hook triggers check at tool_call threshold.

        TOOL_CALL_THRESHOLD = 5 (from custodiet_gate.py)
        """
        cwd = str(tmp_path)

        # First 4 calls don't trigger check
        for i in range(4):
            increment_tool_count(cwd)

        # 5th call should trigger (threshold check in actual hook)
        # We verify state shows we're at threshold
        state = load_custodiet_state(cwd)
        assert state["tool_calls_since_compliance"] == 4

        # After 5th call, hook would spawn custodiet subagent
        increment_tool_count(cwd)
        state = load_custodiet_state(cwd)
        assert state["tool_calls_since_compliance"] == 5

    def test_custodiet_state_keyed_by_project_cwd(self, tmp_path):
        """Verify custodiet state is per-project (by cwd), not per-session.

        This ensures tool counts persist across multiple sessions and subagents.
        """
        project1 = str(tmp_path / "project1")
        project2 = str(tmp_path / "project2")

        Path(project1).mkdir(parents=True)
        Path(project2).mkdir(parents=True)

        # Increment tool count in project1
        increment_tool_count(project1)
        increment_tool_count(project1)

        # Increment tool count in project2
        increment_tool_count(project2)

        # Verify separate state files
        state1 = load_custodiet_state(project1)
        state2 = load_custodiet_state(project2)

        assert state1["tool_calls_since_compliance"] == 2
        assert state2["tool_calls_since_compliance"] == 1


class TestCustodietAxiomChecking:
    """CLAIM 2: Custodiet checks axioms and heuristics."""

    def test_custodiet_audit_context_includes_axioms(self, tmp_path):
        """Verify audit context file includes all axioms for checking."""
        # Load the template that gets written to audit files
        context_file = (
            Path(__file__).parent.parent
            / "hooks"
            / "templates"
            / "custodiet-context.md"
        )

        if context_file.exists():
            content = context_file.read_text()
            # Verify template includes axiom checking section
            assert "AXIOMS" in content or "Axiom" in content
            assert "# HEURISTICS" in content or "heuristic" in content.lower()

    def test_custodiet_instruction_spawns_semantic_agent(self, tmp_path):
        """Verify custodiet instruction spawns haiku subagent for semantic analysis."""

        instruction_file = (
            Path(__file__).parent.parent
            / "hooks"
            / "templates"
            / "custodiet-instruction.md"
        )

        if instruction_file.exists():
            content = instruction_file.read_text()
            # Verify instruction mentions spawning custodiet subagent
            assert 'Task(subagent_type="custodiet"' in content
            assert 'model="haiku"' in content
            # Haiku is semantic analyzer (not reasoning)
            assert "haiku" in content

    def test_custodiet_checks_each_axiom(self):
        """Verify custodiet checks each individual axiom.

        This test documents what axioms custodiet must check.
        See agents/custodiet.md for the agent's checking logic.
        """
        # AXIOMS (from AXIOMS.md)
        axioms_to_check = {
            0: "NO OTHER TRUTHS - agent must not assume/decide anything not derivable",
            1: "CATEGORICAL IMPERATIVE - every action justifiable as universal rule",
            2: "DON'T MAKE SHIT UP - if unknown, say so",
            4: "DO ONE THING - complete task, then STOP",
            8: "FAIL-FAST (Agents) - when tools/instructions fail, STOP immediately",
            16: "NO WORKAROUNDS - if tooling fails, log and HALT",
            17: "VERIFY FIRST - check actual state, never assume",
            22: "ACCEPTANCE CRITERIA OWN SUCCESS - cannot modify/weaken criteria",
        }

        # Custodiet must check all of these
        # (This is documented in audit context templates)
        assert len(axioms_to_check) > 0  # Sanity check


class TestCustodietIssueDetection:
    """CLAIM 3: Custodiet can detect compliance issues."""

    def test_custodiet_output_format_for_violations(self):
        """Verify custodiet returns structured output when issues found.

        From custodiet.md:
        ```
        ATTENTION

        Issue: [1 sentence description]
        Principle: [axiom/heuristic number]
        Correction: [what to do instead]
        ```
        """
        # This documents the expected format custodiet uses
        expected_format = {
            "status": "ATTENTION",  # or "OK"
            "issue": "string",  # 1 sentence
            "principle": "string",  # axiom/heuristic number
            "correction": "string",  # remediation
        }

        # Custodiet parses these fields and returns to main agent
        # (Implementation in agents/custodiet.md)
        assert "status" in expected_format

    def test_custodiet_axiom_4_violation_detection(self):
        """Verify custodiet detects Axiom 4 violation: DO ONE THING.

        Axiom 4: Complete the task requested, then STOP.
        - User asks question → Answer it, then stop
        - User requests task → Do it, then stop
        - Find related issues → Report them, don't fix them

        Custodiet should detect scope drift: agent doing more than asked.
        """
        violation_scenario = {
            "original_request": "Prove custodiet works",
            "agent_actions": [
                "Proved custodiet works",
                "Also refactored hook infrastructure",
                "Also optimized state management",
            ],
        }

        # Custodiet should flag this as scope drift
        # Issue: Agent expanded scope beyond original request
        # Principle: Axiom 4 (DO ONE THING)
        # Correction: Complete requested task, then STOP

        # Original request is present in agent's first action
        assert "custodiet works" in violation_scenario["agent_actions"][0].lower()
        # But scope was expanded with additional tasks
        assert len(violation_scenario["agent_actions"]) > 1

    def test_custodiet_axiom_17_violation_detection(self):
        """Verify custodiet detects Axiom 17 violation: VERIFY FIRST.

        Axiom 17: Check actual state, never assume.
        - Before asserting X, demonstrate evidence for X
        - Reasoning is not evidence; observation is evidence

        Custodiet should detect unverified claims.
        """
        violation_scenario = {
            "claimed_behavior": "The hook works correctly",
            "evidence": None,  # No actual test run
            "reasoning_only": "The code looks correct, so it should work",
        }

        # Custodiet should flag this as unverified assertion
        # Issue: Claimed success without verification/evidence
        # Principle: Axiom 17 (VERIFY FIRST)
        # Correction: Run actual tests and capture evidence

        assert violation_scenario["evidence"] is None

    def test_custodiet_h3_violation_detection(self):
        """Verify custodiet detects H3 violation: VERIFICATION BEFORE ASSERTION.

        H3: Run verification commands BEFORE claiming success, not after.

        Custodiet should detect claims of success without prior verification.
        """
        violation_scenario = {
            "claim": "Custodiet is working",
            "verification_run": False,
            "test_results": None,
        }

        # Custodiet should flag this
        # Issue: Success claimed without prior verification
        # Principle: H3 (VERIFICATION BEFORE ASSERTION)
        # Correction: Run tests first, then claim success

        assert violation_scenario["verification_run"] is False

    def test_custodiet_detects_scope_drift(self):
        """Verify custodiet detects scope drift using drift analysis.

        From custodiet audit template:
        RED FLAGS:
        - Working on tasks not in original request
        - "Improvements" user didn't ask for
        - Expanding scope without explicit approval
        - Modifying files unrelated to task
        - Refactoring "while we're here"
        """
        actual_work = [
            "Test custodiet's detection capabilities",  # In scope
            "Refactor hook infrastructure",  # NOT in scope
            "Optimize state management",  # NOT in scope
        ]

        # Custodiet should detect the last two items as drift
        in_scope = [w for w in actual_work if "detection capabilities" in w]
        out_of_scope = [w for w in actual_work if "Refactor" in w or "Optimize" in w]

        assert len(in_scope) == 1
        assert len(out_of_scope) == 2


class TestCustodietIntegration:
    """Integration tests demonstrating full custodiet workflow."""

    def test_custodiet_workflow_end_to_end(self, tmp_path):
        """Verify complete custodiet workflow:

        1. PostToolUse hook increments tool counter
        2. At threshold, hook spawns custodiet subagent
        3. Custodiet reads audit context
        4. Custodiet checks axioms/heuristics
        5. Custodiet returns compliance status
        6. Main agent receives status and continues or halts
        """
        cwd = str(tmp_path)

        # Step 1: Simulate tool calls
        for _ in range(5):
            increment_tool_count(cwd)

        # Step 2: At threshold, would spawn custodiet
        state = load_custodiet_state(cwd)
        assert state["tool_calls_since_compliance"] == 5

        # Step 3-4: Custodiet would read context and check (simulated)
        # In real execution: Task(subagent_type="custodiet") spawns agent
        # Agent reads /tmp/claude-compliance/audit_*.md
        # Agent checks all axioms/heuristics against context

        # Step 5: Custodiet returns status (OK or ATTENTION)
        # For compliant session: "OK"
        # For violations: structured error with axiom/heuristic

        # Step 6: Main agent continues or halts
        # OK → continue working
        # ATTENTION → HALT and report (Axiom 8: FAIL-FAST)

        # Reset for next cycle
        reset_compliance_state(cwd)
        state = load_custodiet_state(cwd)
        assert state["tool_calls_since_compliance"] == 0


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
