# Nightly aOps bundle sync workflow
# Less invasive alternative - only syncs when aOps has updates
#
# Setup:
# 1. Copy to your project: .github/workflows/sync-aops-nightly.yml
# 2. Commit and push
# 3. Workflow runs nightly at 3am UTC and on manual trigger
#
# This workflow:
# - Checks if aOps has new commits since last sync
# - Only runs sync if updates are available
# - Tracks version in .claude/.aops-version
# - Uses [skip ci] to prevent workflow loops

name: Sync aOps Bundle (Nightly)

on:
  schedule:
    # Run at 3am UTC daily
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: write

jobs:
  check-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current aOps version
        id: current
        run: |
          if [ -f .claude/.aops-version ]; then
            echo "sha=$(cat .claude/.aops-version)" >> $GITHUB_OUTPUT
            echo "Current aOps version: $(cat .claude/.aops-version)"
          else
            echo "sha=" >> $GITHUB_OUTPUT
            echo "No aOps version file found - will sync"
          fi

      - name: Get latest aOps version
        id: latest
        run: |
          LATEST_SHA=$(git ls-remote https://github.com/nicsuzor/academicOps.git HEAD | cut -f1)
          echo "sha=$LATEST_SHA" >> $GITHUB_OUTPUT
          echo "Latest aOps version: $LATEST_SHA"

      - name: Check if update needed
        id: check
        run: |
          if [ "${{ steps.current.outputs.sha }}" = "${{ steps.latest.outputs.sha }}" ]; then
            echo "needs_update=false" >> $GITHUB_OUTPUT
            echo "aOps is up to date - skipping sync"
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "aOps has updates - will sync"
          fi

      - name: Clone aOps framework
        if: steps.check.outputs.needs_update == 'true'
        run: |
          git clone --depth 1 https://github.com/nicsuzor/academicOps.git /tmp/aops

      - name: Set up Python
        if: steps.check.outputs.needs_update == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        if: steps.check.outputs.needs_update == 'true'
        run: |
          pip install pyyaml

      - name: Sync aOps bundle
        if: steps.check.outputs.needs_update == 'true'
        run: |
          cd /tmp/aops
          python scripts/sync_web_bundle.py ${{ github.workspace }} --no-hook --force

      - name: Commit and push
        if: steps.check.outputs.needs_update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .claude/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: sync aOps bundle to ${{ steps.latest.outputs.sha }}

          [skip ci]"
            git push
          fi
