#!/usr/bin/env python3
"""Trace a claude-code-action run to Phoenix with the ida Claude Code tracer.

Writes a Claude Code settings file for claude-code-action's ``settings`` input.
The settings register ``plugins/ida/hooks/claude_code_tracer.py`` as the hooks
for every traced event, and nothing else from the ida plugin, so a CI agent is
traced without inheriting ida's gates.

Configuration comes from the same variables every other surface uses
(``GENAI_ENGINE_TRACE_ENDPOINT``, ``GENAI_ENGINE_API_KEY``,
``GENAI_ENGINE_TRACE_PROTOCOL``). With no endpoint the settings carry no hooks
and the run is untraced. Tracing never fails the run: setup problems degrade
to no hooks with a ``::warning::``, and the hook wrapper always exits 0.

The Access token never enters settings.json, which claude-code-action logs on
a second invocation in the same job. It lives in ``hook.sh`` (mode 0700),
which exports the configuration and runs a private copy of the tracer, so a
branch checkout during the run can't change the tracer.

Usage (stdlib only, so any runner python3 can run it):

    python3 scripts/ci_otel_hooks.py --aops-root <academicOps checkout> \\
        --out-dir "$RUNNER_TEMP/aops-otel" [--project NAME] \\
        [--base-settings FILE] [--python PY]

Writes ``settings=<path>`` to ``$GITHUB_OUTPUT``.
"""

from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path

TRACER_RELPATH = Path("plugins") / "ida" / "hooks" / "claude_code_tracer.py"
DEFAULT_PROJECT = "github-actions"

# Versions locked in uv.lock; the tracer needs nothing else.
TRACER_DEPS = (
    "opentelemetry-sdk==1.44.0",
    "opentelemetry-exporter-otlp-proto-http==1.44.0",
    "requests==2.32.5",
)

# Claude Code hook event -> claude_code_tracer.py event argument.
TRACED_EVENTS = {
    "UserPromptSubmit": "user_prompt_submit",
    "PreToolUse": "pre_tool",
    "PostToolUse": "post_tool",
    "PostToolUseFailure": "post_tool_failure",
    "Stop": "stop",
}
TOOL_EVENTS = {"PreToolUse", "PostToolUse", "PostToolUseFailure"}

CONFIG_ENV = (
    "GENAI_ENGINE_TRACE_ENDPOINT",
    "GENAI_ENGINE_API_KEY",
    "GENAI_ENGINE_TRACE_PROTOCOL",
)
# Captured at setup so spans carry the run's identity even if the agent's
# environment drops them.
RUN_ENV = (
    "GITHUB_ACTIONS",
    "GITHUB_REPOSITORY",
    "GITHUB_RUN_ID",
    "GITHUB_RUN_ATTEMPT",
    "GITHUB_WORKFLOW",
    "GITHUB_JOB",
    "GITHUB_EVENT_NAME",
    "GITHUB_REF",
    "GITHUB_SHA",
    "GITHUB_SERVER_URL",
)


def _load_base(path: str | None) -> dict:
    if not path:
        return {}
    return json.loads(Path(path).read_text(encoding="utf-8"))


def _tracer_python(out_dir: Path, python: str | None) -> str:
    """The interpreter the hooks run the tracer with; builds a venv unless given one."""
    if python:
        return python
    venv = out_dir / "venv"
    subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
    venv_python = venv / "bin" / "python"
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "--quiet", "--disable-pip-version-check", *TRACER_DEPS],
        check=True,
    )
    return str(venv_python)


def _hook_script(python: str, tracer: Path, project: str) -> str:
    lines = ["#!/bin/sh", "# Generated by scripts/ci_otel_hooks.py. Runs the ida tracer for one hook event."]
    exports = {var: os.environ.get(var, "") for var in (*CONFIG_ENV, *RUN_ENV)}
    exports["PHOENIX_PROJECT_NAME"] = project
    for var, value in exports.items():
        if value:
            lines.append(f"export {var}={shlex.quote(value)}")
    lines.append(f'{shlex.quote(python)} {shlex.quote(str(tracer))} "$1" || true')
    lines.append("exit 0")
    return "\n".join(lines) + "\n"


def _hooks(hook_sh: Path) -> dict:
    hooks: dict[str, list] = {}
    for event, tracer_event in TRACED_EVENTS.items():
        entry: dict = {"hooks": [{"type": "command", "command": f"{shlex.quote(str(hook_sh))} {tracer_event}"}]}
        if event in TOOL_EVENTS:
            entry["matcher"] = "*"
        hooks[event] = [entry]
    return hooks


def build_settings(aops_root: Path, out_dir: Path, project: str, base: dict, python: str | None) -> dict:
    if not os.environ.get("GENAI_ENGINE_TRACE_ENDPOINT", "").strip():
        print("::notice::GENAI_ENGINE_TRACE_ENDPOINT is not set; this agent run is not traced to Phoenix.")
        return base

    tracer_src = aops_root / TRACER_RELPATH
    if not tracer_src.is_file():
        print(f"::warning::OTel tracer not found at {tracer_src}; this agent run is not traced.")
        return base

    try:
        tracer = out_dir / tracer_src.name
        shutil.copyfile(tracer_src, tracer)
        tracer_python = _tracer_python(out_dir, python)
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"::warning::OTel tracer setup failed ({exc}); this agent run is not traced.")
        return base

    hook_sh = out_dir / "hook.sh"
    hook_sh.write_text(_hook_script(tracer_python, tracer, project), encoding="utf-8")
    hook_sh.chmod(0o700)

    settings = dict(base)
    hooks = dict(settings.get("hooks", {}))
    for event, entries in _hooks(hook_sh).items():
        hooks[event] = [*hooks.get(event, []), *entries]
    settings["hooks"] = hooks
    print(f"OTel tracing enabled: project {project}, hooks {', '.join(TRACED_EVENTS)}.")
    return settings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--aops-root", required=True, type=Path, help="academicOps checkout holding the tracer")
    parser.add_argument("--out-dir", required=True, type=Path, help="Where settings.json and hook.sh are written")
    parser.add_argument(
        "--project",
        default=os.environ.get("AOPS_OTEL_PROJECT") or DEFAULT_PROJECT,
        help=f"Phoenix project (default: $AOPS_OTEL_PROJECT or {DEFAULT_PROJECT})",
    )
    parser.add_argument("--base-settings", help="Settings JSON to extend rather than replace")
    parser.add_argument("--python", help="Interpreter with the tracer's dependencies; default builds a venv")
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    settings = build_settings(
        args.aops_root.resolve(), args.out_dir.resolve(), args.project, _load_base(args.base_settings), args.python
    )
    settings_path = args.out_dir.resolve() / "settings.json"
    settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")

    if gh_output := os.environ.get("GITHUB_OUTPUT"):
        with open(gh_output, "a", encoding="utf-8") as f:
            f.write(f"settings={settings_path}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
