import os
from pathlib import Path

import yaml

# Configuration
DOCS_DIR = Path("docs")
CONTEXT_INDEX_FILE = Path(".agent/project-context.md")


def parse_frontmatter(file_path):
    """Parse YAML frontmatter from a markdown file."""
    try:
        content = file_path.read_text()
        if content.startswith("---"):
            end_idx = content.find("---", 3)
            if end_idx != -1:
                frontmatter_raw = content[3:end_idx]
                return yaml.safe_load(frontmatter_raw)
    except Exception as e:
        print(f"Error parsing {file_path}: {e}")
    return None


def generate_index():
    """Scan docs and generate project-context.md."""
    if not DOCS_DIR.exists():
        print(f"Docs directory {DOCS_DIR} not found.")
        return

    docs_list = []

    for root, _, files in os.walk(DOCS_DIR):
        for file in files:
            if file.endswith(".md"):
                file_path = Path(root) / file
                meta = parse_frontmatter(file_path)

                # Use frontmatter name/permalink if available, else derive from path
                if meta:
                    topic = meta.get("name") or file_path.stem
                    # Standardize topic title
                    topic = topic.replace("_", " ").title()

                    path = meta.get("permalink") or str(file_path)
                    desc = meta.get("description", "")
                    keywords = meta.get("keywords", [])

                    entry = f"- **{topic}** (`{path}`)"
                    if desc:
                        entry += f": {desc}"
                    if keywords:
                        entry += f" [Keywords: {', '.join(keywords)}]"

                    docs_list.append(entry)
                    print(f"Indexed: {topic}")
                else:
                    # Fallback for files without frontmatter
                    # (Optional: can skip if strict)
                    topic = file_path.stem.replace("_", " ").title()
                    entry = f"- **{topic}** (`{file_path}`)"
                    docs_list.append(entry)

    # Sort alphabetially
    docs_list.sort()

    content = [
        "# Project Context Index",
        "",
        "> **Generated by properties** - Do not edit manually.",
        "",
        "The following documentation is available for this project. If relevant to your task, read the file.",
        "",
    ] + docs_list

    # Ensure .agent exists
    CONTEXT_INDEX_FILE.parent.mkdir(parents=True, exist_ok=True)

    CONTEXT_INDEX_FILE.write_text("\n".join(content))

    print(f"\nGenerated {CONTEXT_INDEX_FILE} with {len(docs_list)} entries.")


if __name__ == "__main__":
    generate_index()
