#!/usr/bin/env python3
"""
Generate AXIOMS.md and HEURISTICS.md from individual principle files.

Reads axioms/ and heuristics/ folders, extracts frontmatter and content,
generates machine-readable index files for agent consumption.

Usage:
    uv run python scripts/generate_principle_indices.py
    uv run python scripts/generate_principle_indices.py --check  # Verify only, no write
"""

import argparse
import re
import sys
from pathlib import Path

import yaml


def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Extract YAML frontmatter and body from markdown file."""
    if not content.startswith("---"):
        return {}, content

    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}, content

    try:
        frontmatter = yaml.safe_load(parts[1])
        body = parts[2].strip()
        return frontmatter or {}, body
    except yaml.YAMLError:
        return {}, content


def extract_statement(body: str) -> str:
    """Extract the statement from the body (first **Statement**: line or first paragraph after heading)."""
    # Look for explicit **Statement**: pattern
    match = re.search(r"\*\*Statement\*\*:\s*(.+?)(?:\n\n|\n##|\Z)", body, re.DOTALL)
    if match:
        return match.group(1).strip()

    # Fallback: first non-empty paragraph after the heading
    lines = body.split("\n")
    in_content = False
    paragraph = []
    for line in lines:
        if line.startswith("# "):
            in_content = True
            continue
        if in_content:
            if line.strip():
                paragraph.append(line.strip())
            elif paragraph:
                break
    return " ".join(paragraph) if paragraph else ""


def extract_corollary(body: str) -> str | None:
    """Extract corollary if present."""
    match = re.search(r"## Corollary\s*\n\n(.+?)(?:\n\n##|\Z)", body, re.DOTALL)
    if match:
        return match.group(1).strip()
    return None


def load_principles(folder: Path) -> list[dict]:
    """Load all principle files from a folder.

    Priority bands (1-100):
    - 1-20: Core principles (inviolable axioms, fundamental heuristics)
    - 21-40: Behavioral rules (agent conduct)
    - 41-60: Domain-specific (Python, framework, features)
    - 61-80: Derived/supporting rules
    - 81-100: Experimental/provisional
    """
    principles = []
    for file in sorted(folder.glob("*.md")):
        if file.name in ("INDEX.md", "README.md"):
            continue

        content = file.read_text()
        frontmatter, body = parse_frontmatter(content)

        if not frontmatter.get("name"):
            print(f"WARNING: {file} missing 'name' in frontmatter", file=sys.stderr)
            continue

        principle = {
            "name": frontmatter["name"],
            "title": frontmatter.get("title", frontmatter["name"]),
            "priority": frontmatter.get("priority", 50),  # Default to mid-range
            "statement": extract_statement(body),
            "corollary": extract_corollary(body),
            "file": file.name,
        }
        principles.append(principle)

    # Sort by priority (lower = more important)
    return sorted(principles, key=lambda p: (p.get("priority", 50), p["name"]))


def generate_axioms_md(principles: list[dict]) -> str:
    """Generate AXIOMS.md content."""
    lines = [
        "---",
        "name: axioms",
        "title: Universal Principles",
        "type: instruction",
        "category: instruction",
        "description: Generated index of axioms. Do not edit manually.",
        "permalink: axioms",
        "tags: [framework, principles, core, generated]",
        "---",
        "",
        "> **Generated by audit skill** - Do not edit manually.",
        "> Source: `axioms/` folder. Regenerate with `uv run python scripts/generate_principle_indices.py`",
        "",
        "# Universal Principles",
        "",
        "Inviolable rules. Full definitions with evidence: see individual files in `axioms/` folder.",
        "",
        "| Pri | Name | Statement |",
        "|-----|------|-----------|",
    ]

    for p in principles:
        pri = p.get("priority", 50)
        name_link = f"[[{p['name']}]]"
        statement = (
            p["statement"][:100] + "..."
            if len(p["statement"]) > 100
            else p["statement"]
        )
        statement = statement.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {pri} | {name_link} | {statement} |")

    lines.extend(
        [
            "",
            "## Corollaries",
            "",
        ]
    )

    has_corollary = False
    for p in principles:
        if p["corollary"]:
            has_corollary = True
            lines.append(f"**{p['title']}**: {p['corollary']}")
            lines.append("")

    if not has_corollary:
        lines.append("_No corollaries defined._")
        lines.append("")

    return "\n".join(lines)


def generate_heuristics_md(principles: list[dict]) -> str:
    """Generate HEURISTICS.md content."""
    lines = [
        "---",
        "name: heuristics",
        "title: Heuristics",
        "type: instruction",
        "category: instruction",
        "description: Generated index of heuristics. Do not edit manually.",
        "permalink: heuristics",
        "tags: [framework, heuristics, empirical, generated]",
        "---",
        "",
        "> **Generated by audit skill** - Do not edit manually.",
        "> Source: `heuristics/` folder. Regenerate with `uv run python scripts/generate_principle_indices.py`",
        "",
        "# Heuristics",
        "",
        "Working hypotheses validated by evidence. Full definitions: see `heuristics/` folder.",
        "",
        "| Pri | Name | Statement |",
        "|-----|------|-----------|",
    ]

    for p in principles:
        pri = p.get("priority", 50)
        name_link = f"[[{p['name']}]]"
        statement = (
            p["statement"][:100] + "..."
            if len(p["statement"]) > 100
            else p["statement"]
        )
        statement = statement.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {pri} | {name_link} | {statement} |")

    lines.extend(
        [
            "",
            "## Domain-Specific Heuristics",
            "",
            "Some heuristics apply only within specific domains. See the relevant skill:",
            "",
            "- **Framework development**: `framework` skill",
            "- **Feature development**: `feature-dev` skill",
            "- **Knowledge persistence**: `remember` skill",
            "- **Research data**: `analyst` skill",
            "- **Task management**: `tasks` skill",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate principle index files")
    parser.add_argument(
        "--check", action="store_true", help="Check only, don't write files"
    )
    parser.add_argument(
        "--aops", type=Path, default=None, help="Path to academicOps root"
    )
    args = parser.parse_args()

    # Find academicOps root
    if args.aops:
        aops = args.aops
    else:
        # Try to find it relative to script location
        script_dir = Path(__file__).parent
        aops = script_dir.parent
        if not (aops / "axioms").exists():
            print(
                "ERROR: Cannot find axioms/ folder. Use --aops to specify path.",
                file=sys.stderr,
            )
            return 1

    axioms_folder = aops / "axioms"
    heuristics_folder = aops / "heuristics"

    if not axioms_folder.exists():
        print(f"ERROR: {axioms_folder} does not exist", file=sys.stderr)
        return 1
    if not heuristics_folder.exists():
        print(f"ERROR: {heuristics_folder} does not exist", file=sys.stderr)
        return 1

    # Load principles
    axioms = load_principles(axioms_folder)
    heuristics = load_principles(heuristics_folder)

    print(f"Loaded {len(axioms)} axioms, {len(heuristics)} heuristics")

    # Generate content
    axioms_content = generate_axioms_md(axioms)
    heuristics_content = generate_heuristics_md(heuristics)

    if args.check:
        # Check mode: compare with existing files
        axioms_file = aops / "AXIOMS.md"
        heuristics_file = aops / "HEURISTICS.md"

        errors = 0
        if axioms_file.exists():
            existing = axioms_file.read_text()
            if existing != axioms_content:
                print("AXIOMS.md is out of date - regenerate with this script")
                errors += 1
            else:
                print("AXIOMS.md is up to date")
        else:
            print("AXIOMS.md does not exist - generate with this script")
            errors += 1

        if heuristics_file.exists():
            existing = heuristics_file.read_text()
            if existing != heuristics_content:
                print("HEURISTICS.md is out of date - regenerate with this script")
                errors += 1
            else:
                print("HEURISTICS.md is up to date")
        else:
            print("HEURISTICS.md does not exist - generate with this script")
            errors += 1

        return errors

    # Write files
    axioms_file = aops / "AXIOMS.md"
    heuristics_file = aops / "HEURISTICS.md"

    axioms_file.write_text(axioms_content)
    print(f"Generated {axioms_file}")

    heuristics_file.write_text(heuristics_content)
    print(f"Generated {heuristics_file}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
