#!/usr/bin/env bash
# polecat.sh (aliased as pc) - Launch Docker Sandboxes (sbx) with academicOps framework & kits from any repository.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AOPS_ROOT="${AOPS_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

show_help() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS] [AGENT] [WORKSPACE_PATH] [-- AGENT_ARGS...]

Launch or create a Docker Sandbox (sbx) with academicOps framework kits.

Arguments:
  AGENT           Agent to run: 'agy' (default) or 'claude'
  WORKSPACE_PATH  Path to the target repository/workspace (default: '.')

Options:
  -c, --clone     Use isolated in-container git clone (--clone)
  -n, --name NAME Sandbox name (default: auto-generated by sbx)
  -d, --create    Create the sandbox only without attaching immediately
  -h, --help      Show this help message

Environment Variables forwarded automatically:
  PKB_MCP_URL, GENAI_ENGINE_TRACE_ENDPOINT, AOPS_BOT_GH_TOKEN,
  CLAUDE_CODE_OAUTH_TOKEN, GEMINI_API_KEY

Examples:
  # Run agy on the current directory from any repo
  pc

  # Run claude on another project
  pc claude /path/to/project

  # Run an isolated git clone worker with custom name and task prompt
  pc --clone --name task-123 agy . -- -p "/aops:pull 123"
EOF
}

CLONE=0
CREATE_ONLY=0
SANDBOX_NAME=""
AGENT=""
WORKSPACE=""
EXTRA_AGENT_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      show_help
      exit 0
      ;;
    -c|--clone)
      CLONE=1
      shift
      ;;
    -d|--create)
      CREATE_ONLY=1
      shift
      ;;
    -n|--name)
      SANDBOX_NAME="$2"
      shift 2
      ;;
    --)
      shift
      EXTRA_AGENT_ARGS=("$@")
      break
      ;;
    -*)
      echo "Unknown option: $1" >&2
      show_help >&2
      exit 1
      ;;
    *)
      if [ -z "$AGENT" ]; then
        AGENT="$1"
      elif [ -z "$WORKSPACE" ]; then
        WORKSPACE="$1"
      else
        echo "Unexpected argument: $1" >&2
        show_help >&2
        exit 1
      fi
      shift
      ;;
  esac
done

AGENT="${AGENT:-agy}"
WORKSPACE="${WORKSPACE:-.}"

if [[ "$AGENT" != "agy" && "$AGENT" != "claude" ]]; then
  echo "Error: Supported agents are 'agy' or 'claude', got: '$AGENT'" >&2
  exit 1
fi

AGENT_KIT="$AOPS_ROOT/lib/kits/$AGENT"
AOPS_KIT="$AOPS_ROOT/lib/kits/aops"

if [ ! -f "$AGENT_KIT/spec.yaml" ]; then
  echo "Error: Agent kit not found at $AGENT_KIT" >&2
  exit 1
fi

if [ ! -f "$AOPS_KIT/spec.yaml" ]; then
  echo "Error: Framework mixin kit not found at $AOPS_KIT" >&2
  exit 1
fi

CMD_ARGS=()
if [ "$CLONE" -eq 1 ]; then
  CMD_ARGS+=(--clone)
fi

if [ -n "$SANDBOX_NAME" ]; then
  CMD_ARGS+=(--name "$SANDBOX_NAME")
fi

CMD_ARGS+=(--kit "$AGENT_KIT" --kit "$AOPS_KIT")

# Forward known framework environment variables if present
for var in PKB_MCP_URL GENAI_ENGINE_TRACE_ENDPOINT AOPS_BOT_GH_TOKEN CLAUDE_CODE_OAUTH_TOKEN GEMINI_API_KEY; do
  if [ -n "${!var:-}" ]; then
    CMD_ARGS+=(-e "$var")
  fi
done

CMD_ARGS+=("$AGENT" "$WORKSPACE")

if [ "$CREATE_ONLY" -eq 1 ]; then
  echo "==> Creating sbx sandbox: ${SANDBOX_NAME:-auto} ($AGENT) in $WORKSPACE"
  sbx create "${CMD_ARGS[@]}"
  
  if [ -n "${PKB_MCP_URL:-}" ] && [ -n "$SANDBOX_NAME" ]; then
    PKB_HOST=$(echo "$PKB_MCP_URL" | sed -E 's|^https?://([^/:]+).*|\1|')
    sbx policy allow network --sandbox "$SANDBOX_NAME" "$PKB_HOST:443" >/dev/null 2>&1 || true
  fi
else
  echo "==> Running sbx sandbox: ${SANDBOX_NAME:-auto} ($AGENT) in $WORKSPACE"
  if [ ${#EXTRA_AGENT_ARGS[@]} -gt 0 ]; then
    exec sbx run "${CMD_ARGS[@]}" -- "${EXTRA_AGENT_ARGS[@]}"
  else
    exec sbx run "${CMD_ARGS[@]}"
  fi
fi
