import sys
from pathlib import Path
import pytest

# Add repo root and aops-core to path
repo_root = Path(__file__).parent.parent
sys.path.insert(0, str(repo_root))
sys.path.insert(0, str(repo_root / "aops-core"))


@pytest.mark.demo
def test_load_project_context_index():
    print("Testing load_project_context_index with .agent/project-context.md...")

    # Setup: Create dummy project-context.md
    context_file = Path(".agent/project-context.md")
    context_file.parent.mkdir(exist_ok=True)

    dummy_content = """# Project Context Index

> Generated by properties

- **Project Structure** (`docs/structure.md`): Overview of project layout [Keywords: architecture, structure]
- **Database** (`docs/db.md`): Database models [Keywords: db, sql]
"""
    context_file.write_text(dummy_content)

    try:
        # Import the hook function
        # Now that aops-core is in path, we can import hooks
        from hooks.user_prompt_submit import load_project_context_index

        index_content = load_project_context_index()

        print("\n--- Generated Index Content ---")
        print(index_content)
        print("-------------------------------\n")

        # Verify content
        if "- **Project Structure**" in index_content:
            print("✅ Verification PASSED: 'Project Structure' found in index")
        else:
            print("❌ Verification FAILED: 'Project Structure' NOT found in index")

        if "docs/structure.md" in index_content:
            print("✅ Verification PASSED: Path found in index")

        # Verify header stripping
        if "# Project Context Index" not in index_content:
            print("✅ Verification PASSED: Header stripped correctly")
        else:
            print("⚠️ Verification WARNING: Header not stripped (might be acceptable)")

    finally:
        # Cleanup
        if context_file.exists():
            context_file.unlink()


if __name__ == "__main__":
    try:
        test_load_project_context_index()
        print("\nAll tests passed!")
    except ImportError as e:
        print(f"Import failed: {e}")
        print("Make sure aops-core is in pythonpath")
    except Exception as e:
        print(f"Test failed: {e}")
        import traceback

        traceback.print_exc()
